### ISSUE TITLE
"logomaker.alignment_to_matrix" returns wrong matrix

### ISSUE THREAD

**Issue by ponnhide** [jbkinney/logomaker#6]
I was looking for drawing motif logo using native matplotlib module. This library is really great!
However,  I encountered an issue, when I was used the method which is "logomaker.alignment_to_matrix(sequence_list, to_type="probability")". 
The method returned the wrong probability matrix. Probably, the method counted the non-existing characters.

I used the following sequence list and got the following motif logo. The figure shows the information contents of the non-existing characters.
Do you have any idea to solve the problem?
````
sequence_list = ['LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG']
````

![image](https://user-images.githubusercontent.com/2762763/64470326-7f18ea80-d17c-11e9-8d3c-4bf4a317ff50.png)

**Comment by atareen** [comment]
Hi Ponnhide, 

Thanks for using logomaker and thanks for pointing this out.

As a temporary work-around, you could use the following code:

`counts_df = logomaker.alignment_to_matrix(sequence_list)`
`prob_df = logomaker.transform_matrix(counts_df,normalize_values=True)`
`logomaker.Logo(prob_df)`

I will look into the to_type='probability' issue soon.

Thanks again,
-Ammar

**Comment by jbkinney** [comment]
The issue is that, when you call 

`logomaker.alignment_to_matrix(sequence_list, to_type="probability")`

logomaker assumes a pseudocount of 1. So if you have a small number of sequences, this pseudocount will have a big effect. Just set `pseudocount=0` in the call to `alignment_to_matrix` and this will be resolved. My code is below; I've also attached my jupyter notebook. 
![pseudocount](https://user-images.githubusercontent.com/7266668/64476927-1709da80-d163-11e9-8a6a-11c52e8093c6.png)


`import matplotlib.pyplot as plt
import logomaker 
%matplotlib inline

sequence_list = ['LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG', 'LTPAQVVAIASNIGGKQALETVQRLLPVLCQAHG', 'LTPEQVVAIASHDGGKQALETVQRLLPVLCQAHG']

fig, axs = plt.subplots(2,1)

# With default pseudocount
prob_mat = logomaker.alignment_to_matrix(sequence_list, 
                                         to_type='probability')
logomaker.Logo(prob_mat, 
               ax=axs[0], 
               color_scheme='weblogo_protein', 
               show_spines=False)

# With pseudocount=0
prob_mat = logomaker.alignment_to_matrix(sequence_list, 
                                         to_type='probability', 
                                         pseudocount=0)
logomaker.Logo(prob_mat,
               ax=axs[1], 
               color_scheme='weblogo_protein', 
               show_spines=False)`

**Comment by jbkinney** [comment]
The previous email was strange looking. Sorry. 

Just add the keyword argument `pseudocount=0` when you call `logomaker.alignment_to_matrix()` and it should work. Here's what I get:

![image](https://user-images.githubusercontent.com/7266668/64476970-98fa0380-d163-11e9-8bea-e3f51347b886.png)

**Comment by ponnhide** [comment]
Thank you for your prompt response. 
I should have read the document in detail before open the issue. 
By following your comment, I got the collect motif logo. 
Thank you!
